"""messages表加token_count和model_name

Revision ID: 3c1e05cbe765
Revises: eed8d88c9406
Create Date: 2026-04-25 11:05:34.832391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1e05cbe765'
down_revision: Union[str, Sequence[str], None] = 'eed8d88c9406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('model_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model_name')
    op.drop_column('messages', 'token_count')
    # ### end Alembic commands ###
